FROM python:3.6-alpine
COPY ./backend/requirements.txt /
RUN pip install -r /requirements.txt
RUN pip install gunicorn

COPY ./backend /app
WORKDIR /app

CMD ["gunicorn", "-w 4", "-b 0.0.0.0:5000", "wsgi:app"]