FROM node:alpine AS build-env
WORKDIR /app
COPY ./package*.json /app/
RUN npm install
COPY ./ /app/
RUN npm run build

FROM nginx:alpine
WORKDIR /app
COPY --from=build-env /app/build /app
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf